//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stealth_Compressor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int COMPRESSION_LEVEL {
            get {
                return ((int)(this["COMPRESSION_LEVEL"]));
            }
            set {
                this["COMPRESSION_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deflate")]
        public string COMPRESSION_METHOD {
            get {
                return ((string)(this["COMPRESSION_METHOD"]));
            }
            set {
                this["COMPRESSION_METHOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string COMPRESSION_STRATEGY {
            get {
                return ((string)(this["COMPRESSION_STRATEGY"]));
            }
            set {
                this["COMPRESSION_STRATEGY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4096")]
        public int IO_BUFFER_SIZE {
            get {
                return ((int)(this["IO_BUFFER_SIZE"]));
            }
            set {
                this["IO_BUFFER_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4096")]
        public int CODEC_BUFFER_SIZE {
            get {
                return ((int)(this["CODEC_BUFFER_SIZE"]));
            }
            set {
                this["CODEC_BUFFER_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MEMORY_ARCHIVE {
            get {
                return ((bool)(this["MEMORY_ARCHIVE"]));
            }
            set {
                this["MEMORY_ARCHIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("As Needed")]
        public string USE_ZIP64 {
            get {
                return ((string)(this["USE_ZIP64"]));
            }
            set {
                this["USE_ZIP64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENCRYPT_ARCHIVE {
            get {
                return ((bool)(this["ENCRYPT_ARCHIVE"]));
            }
            set {
                this["ENCRYPT_ARCHIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PASSWORD_MASK {
            get {
                return ((bool)(this["PASSWORD_MASK"]));
            }
            set {
                this["PASSWORD_MASK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PASSWORD_VALIDATE {
            get {
                return ((bool)(this["PASSWORD_VALIDATE"]));
            }
            set {
                this["PASSWORD_VALIDATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******")]
        public string PASSWORD_FORMAT {
            get {
                return ((string)(this["PASSWORD_FORMAT"]));
            }
            set {
                this["PASSWORD_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PkzipWeak")]
        public string ENCRYPTION_ALGORITHM {
            get {
                return ((string)(this["ENCRYPTION_ALGORITHM"]));
            }
            set {
                this["ENCRYPTION_ALGORITHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPEN_ON_COMPLETION {
            get {
                return ((bool)(this["OPEN_ON_COMPLETION"]));
            }
            set {
                this["OPEN_ON_COMPLETION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALERT_ON_COMPLETION {
            get {
                return ((bool)(this["ALERT_ON_COMPLETION"]));
            }
            set {
                this["ALERT_ON_COMPLETION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KB")]
        public string UNITS {
            get {
                return ((string)(this["UNITS"]));
            }
            set {
                this["UNITS"] = value;
            }
        }
    }
}
